source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'cineio-broadcast-ios', '~> 0.7'
#pod 'cineio-broadcast-ios', path: '/Users/jeffrey/dev/cine-dev/cineio-broadcast-ios'
#pod 'VideoCore', path: '/Users/jeffrey/dev/cine-dev/VideoCore'

pod 'AFNetworking', '~> 2.5'
pod 'NSURL+ParseQuery', '~> 0.1'
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'SSKeychain', '~> 1.2.2'